name: .NET build

on:
  push:
    branches: [ "main" ]
    paths:
      - 'C# Solution/**'
  pull_request:
    branches: [ "main" ]
    paths:
      - 'C# Solution/**'

jobs:
  build:

    runs-on: windows-2022

    steps:
    - uses: actions/checkout@v4
        
    - name: Build
      run: |
        cd "C# Solution"
        dotnet restore Dw2Doc.sln
        dotnet publish Dw2Doc.sln --configuration Release -r windows -f net8.0-windows
        dotnet publish Dw2Doc.sln --configuration Release -r windows -f net481
        dotnet publish Dw2Doc.sln --configuration Release -r windows -f net6.0-windows
      
    - name: Test
      run: |
        cd "C# Solution"
        dotnet test Dw2Doc.Tests/Dw2Doc.Tests.csproj -f net8.0-windows --no-build --verbosity normal
        dotnet test Dw2Doc.Tests/Dw2Doc.Tests.csproj -f net481 --no-build --verbosity normal
        dotnet test Dw2Doc.Tests/Dw2Doc.Tests.csproj -f net6.0-windows --no-build --verbosity normal
